[pytest]
python_files = test_*.py

# Add project root to Python path
python_paths = 
    .
    auto_job_apply
    api_app

# Configure test discovery
testpaths = tests

# Set default options
addopts = -v --tb=short
